import {
  AppWindow,
  Calculator,
  CloudSun,
  Code2,
  Cpu,
  FolderOpen,
  Gamepad2,
  ImageIcon,
  Info,
  Monitor,
  Newspaper,
  Search,
  Settings as SettingsIcon,
  Sparkles,
  StickyNote,
  Terminal,
} from "lucide-react";
import type { AppId } from "../types";
import type { ComponentType } from "react";

export interface AppMeta {
  id: AppId;
  name: string;
  icon: ComponentType<{ size?: number | string; className?: string; strokeWidth?: number }>;
  defaultSize: { w: number; h: number };
  minSize?: { w: number; h: number };
  showInDock?: boolean;
  showInLauncher?: boolean;
  resizable?: boolean;
  description: string;
  accent?: string;
}

export const APPS: Record<AppId, AppMeta> = {
  links: {
    id: "links",
    name: "Quick Links",
    icon: AppWindow,
    defaultSize: { w: 880, h: 580 },
    minSize: { w: 520, h: 380 },
    showInDock: true,
    showInLauncher: true,
    resizable: true,
    description: "Your favorite places on the web.",
  },
  search: {
    id: "search",
    name: "Search",
    icon: Search,
    defaultSize: { w: 720, h: 220 },
    minSize: { w: 520, h: 200 },
    showInDock: true,
    showInLauncher: true,
    resizable: true,
    description: "Search the web with multiple engines.",
  },
  terminal: {
    id: "terminal",
    name: "Terminal",
    icon: Terminal,
    defaultSize: { w: 760, h: 460 },
    minSize: { w: 460, h: 260 },
    showInDock: true,
    showInLauncher: true,
    resizable: true,
    description: "An interactive shell.",
  },
  files: {
    id: "files",
    name: "Files",
    icon: FolderOpen,
    defaultSize: { w: 820, h: 540 },
    minSize: { w: 520, h: 360 },
    showInDock: true,
    showInLauncher: true,
    resizable: true,
    description: "Browse your bookmarks like files.",
  },
  notes: {
    id: "notes",
    name: "Notes",
    icon: StickyNote,
    defaultSize: { w: 700, h: 500 },
    minSize: { w: 460, h: 340 },
    showInDock: true,
    showInLauncher: true,
    resizable: true,
    description: "Markdown notes with live preview — saved locally.",
  },
  weather: {
    id: "weather",
    name: "Weather",
    icon: CloudSun,
    defaultSize: { w: 540, h: 400 },
    minSize: { w: 420, h: 360 },
    showInDock: false,
    showInLauncher: true,
    resizable: true,
    description: "Live weather for your city.",
  },
  clock: {
    id: "clock",
    name: "Clock",
    icon: Sparkles,
    defaultSize: { w: 480, h: 360 },
    minSize: { w: 380, h: 320 },
    showInDock: false,
    showInLauncher: true,
    resizable: true,
    description: "World clock & timer.",
  },
  calculator: {
    id: "calculator",
    name: "Calculator",
    icon: Calculator,
    defaultSize: { w: 360, h: 480 },
    minSize: { w: 320, h: 440 },
    showInDock: false,
    showInLauncher: true,
    resizable: false,
    description: "A simple calculator.",
  },
  monitor: {
    id: "monitor",
    name: "System Monitor",
    icon: Cpu,
    defaultSize: { w: 560, h: 420 },
    minSize: { w: 460, h: 360 },
    showInDock: false,
    showInLauncher: true,
    resizable: true,
    description: "Live (simulated) system stats.",
  },
  reader: {
    id: "reader",
    name: "Reader",
    icon: Newspaper,
    defaultSize: { w: 980, h: 640 },
    minSize: { w: 620, h: 420 },
    showInDock: true,
    showInLauncher: true,
    resizable: true,
    description: "Tech, AI, and security news.",
  },
  games: {
    id: "games",
    name: "Games",
    icon: Gamepad2,
    defaultSize: { w: 720, h: 620 },
    minSize: { w: 480, h: 420 },
    showInDock: false,
    showInLauncher: true,
    resizable: true,
    description: "Retro emulator (NES, SNES, GB/C/A, N64).",
  },
  vnc: {
    id: "vnc",
    name: "Remote Desktop",
    icon: Monitor,
    defaultSize: { w: 1100, h: 720 },
    minSize: { w: 600, h: 400 },
    showInDock: false,
    showInLauncher: true,
    resizable: true,
    description: "noVNC client — connect to a VNC server via websockify.",
  },
  code: {
    id: "code",
    name: "Code",
    icon: Code2,
    defaultSize: { w: 1080, h: 700 },
    minSize: { w: 600, h: 420 },
    showInDock: true,
    showInLauncher: true,
    resizable: true,
    description: "Monaco editor scratchpad + remote VS Code launchers.",
  },
  bitmappery: {
    id: "bitmappery",
    name: "Paint",
    icon: ImageIcon,
    defaultSize: { w: 1080, h: 720 },
    minSize: { w: 640, h: 440 },
    showInDock: false,
    showInLauncher: true,
    resizable: true,
    description:
      "Bundled image editor (Toast UI): crop, filters, draw, text — runs entirely in-browser.",
  },
  settings: {
    id: "settings",
    name: "Settings",
    icon: SettingsIcon,
    defaultSize: { w: 820, h: 580 },
    minSize: { w: 580, h: 420 },
    showInDock: true,
    showInLauncher: true,
    resizable: true,
    description: "Wallpaper, accent, theme.",
  },
  about: {
    id: "about",
    name: "About",
    icon: Info,
    defaultSize: { w: 520, h: 380 },
    minSize: { w: 420, h: 320 },
    showInDock: false,
    showInLauncher: true,
    resizable: true,
    description: "About this OS.",
  },
};

// Quick-launch order used in waybar favorites
export const FAVORITES: AppId[] = [
  "terminal",
  "links",
  "files",
  "reader",
  "notes",
];
